Repository bcgov/sso-requests, pull requests merged in 2023-12, with the labels that each got.

#1091 chore: label action
  .github/workflows/check-labels.yaml
Labels: enhancement

#1090 chore: messaging
  app/schemas/providers.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/actions/src/controllers/batch.ts
  lambda/shared/templates/bceid-warning.html
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
Labels: enhancement

#1092 fix: missing tab
  app/jest/integrationTabs.test.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
Labels: bug

#1093 chore: duplicated user
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/app/src/controllers/user.ts
Labels: bug

#1094 chore: release
  .github/workflows/check-labels.yaml
  .github/workflows/deploy-gh-pages-maintenance.yml
  app/components/GenericModal.tsx
  app/components/InstallationPanel.tsx
  app/components/RequestPreview.tsx
  app/form-components/FormTemplate.tsx
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/jest/integrationTabs.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/samples/integrations.ts
  app/page-partials/faq/FaqItems.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/RoleManagement/index.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  app/page-partials/my-dashboard/UserRoles.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/index.ts
  app/schemas/providers.ts
  app/schemas/requester-info.ts
  app/services/request.ts
  app/styles/globals.css
  app/yarn.lock
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/__tests__/helpers/fixtures.ts
  lambda/actions/src/controllers/batch.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/user.ts
  lambda/db/src/migrations/2023.11.09T15.37.58.add-primary-users.ts
  lambda/db/src/umzug.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/bceid-warning.html
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/integration-detail.html
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  terraform/ecs.tf
  terraform/s3-bucket/main.tf
  terraform/variables-grafana.tf
Labels: release:minor

#1096 chore: change grafana api route
  .github/workflows/terraform.yml
  lambda/app/src/controllers/logs.ts
  lambda/app/src/grafana.ts
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: feature

#1097 feat: metrics tab implementation to query aggregated logs from grafana
  app/components/DateTimePicker.tsx
  app/interfaces/Request.ts
  app/package.json
  app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/services/grafana.ts
  app/yarn.lock
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/controllers/logs.ts
  lambda/app/src/grafana.ts
  lambda/app/src/routes.ts
  localserver/.env.example
Labels: enhancement

#1098 feat: validations for start and end dates
  app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
  app/utils/helpers.tsx
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/app/src/controllers/logs.ts
  lambda/app/src/grafana.ts
Labels: enhancement

#1099 chore: release
  .github/workflows/terraform.yml
  app/components/DateTimePicker.tsx
  app/interfaces/Request.ts
  app/package.json
  app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/services/grafana.ts
  app/utils/helpers.tsx
  app/yarn.lock
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/controllers/logs.ts
  lambda/app/src/grafana.ts
  lambda/app/src/routes.ts
  localserver/.env.example
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: release:minor

#1100 feat: role migration script
  .gitignore
  role-migration/.env.example
  role-migration/.tool-versions
  role-migration/README.md
  role-migration/get-keycloak-roles.js
  role-migration/package.json
  role-migration/yarn.lock
Labels: feature
