Repository bcgov/sso-requests, pull requests merged in 2023-11, with the labels that each got.

#1054 chore: remove bucket
  terraform/env-resources.tf_dev
Labels: bug

#1052 feat: vc updates
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/TooltipCheckboxesWidget.tsx
  app/helpers/integration.ts
  app/helpers/meta.ts
  app/interfaces/Request.ts
  app/next.config.js
  app/page-partials/admin-dashboard/AdminTabs/DigitalCredentialTabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/page-partials/my-dashboard/UserRoles.tsx
  app/pages/admin-dashboard.tsx
  app/schemas/providers-gold.ts
  app/utils/helpers.tsx
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/actions/src/controllers/batch.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/github.ts
  lambda/db/src/migrations/2023.11.01T13.26.56.update-vc-name.ts
  lambda/db/src/umzug.ts
  lambda/shared/local.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/create-verified-credential-bottom.html
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: feature

#1057 fix: outlook bug
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/create-github-bottom.html
Labels: bug

#1058 chore: idp display
  app/helpers/integration.ts
  app/utils/helpers.tsx
Labels: enhancement

#1062 chore: row selection
  app/components/TableNew.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/TeamList.tsx
Labels: bug

#1063 fix: empty fields
  app/services/request.ts
Labels: bug

#1066 chore: dit email
  app/form-components/FormTemplate.tsx
Labels: enhancement

#1081 chore: links
  app/components/InstallationPanel.tsx
  app/form-components/FormTemplate.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/page-partials/faq/FaqItems.tsx
  app/schemas/providers.ts
Labels: enhancement

#1080 feat: users
  app/components/RequestPreview.tsx
  app/form-components/FormTemplate.tsx
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/jest/samples/integrations.ts
  app/schemas-ui/ui-gold.ts
  app/schemas/index.ts
  app/schemas/requester-info.ts
  app/services/request.ts
  app/styles/globals.css
  app/yarn.lock
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/__tests__/helpers/fixtures.ts
  lambda/actions/src/controllers/batch.ts
  lambda/app/src/controllers/requests.ts
  lambda/db/src/migrations/2023.11.09T15.37.58.add-primary-users.ts
  lambda/db/src/umzug.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/integration-detail.html
Labels: enhancement

#1082 chore: default val
  app/services/request.ts
Labels: bug

#1084 feat: upgrade grafana to 10.2.2
  terraform/variables-grafana.tf
Labels: enhancement
