Repository bcgov/sso-requests, pull requests merged in 2024-08, with the labels that each got.

#1260 chore: update the client testimonials
  app/utils/constants.ts
Labels: enhancement

#1262 chore: update colours on css
  app/layout/BCSans.tsx
  app/package.json
  app/styles/globals.css
  app/yarn.lock
Labels: enhancement

#1263 chore: widget type
  app/form-components/FieldAccessTokenLifespan.tsx
  app/form-components/FieldAccessTokenTop.tsx
  app/form-components/FieldInlineGrid.tsx
  app/form-components/widgets/ClientTokenWidget.tsx
  app/form-components/widgets/MinutesToSeconds.tsx
  app/form-components/widgets/SwitchWidget.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  tsconfig.json
Labels: enhancement

#1264 chore: accesibility changes
  app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
  app/svg/StandardRealms.tsx
Labels: enhancement

#1261 feat: use react bootstrap modal and updated unit tests
  app/components/ActionButtons.tsx
  app/components/CenteredModal.tsx
  app/components/DeleteModal.tsx
  app/form-components/FieldProjectTeam.tsx
  app/form-components/FieldRequesterInfo.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/team-form/CreateTeamForm.tsx
  app/form-components/team-form/EditTeamNameForm.tsx
  app/jest/form.test.tsx
  app/jest/layout.test.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-projects/secrets.test.tsx
  app/jest/my-dashboard/my-teams/cssApiAccount.test.tsx
  app/jest/my-dashboard/my-teams/integrations.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/layout/GoldNotificationModal.tsx
  app/layout/Layout.tsx
  app/layout/UserProfileModal.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/MetadataEditModal.tsx
  app/page-partials/edit-request/CancelConfirmModal.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/page-partials/my-dashboard/SecretsPanel.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  app/page-partials/my-dashboard/TeamList.tsx
  app/pages/admin-dashboard.tsx
  app/pages/my-dashboard/integrations.tsx
  app/styles/globals.css
  app/utils/constants.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/routes.ts
Labels: enhancement

#1265 feat: default values team
  app/form-components/FieldTemplate.tsx
  app/form-components/widgets/SwitchWidget.tsx
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/requester-info.ts
Labels: enhancement

#1266 feat: enable sso admins with read only access to roles
  app/jest/ssoDashboard.test.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/RoleManagement/CreateRoleContent.tsx
  app/page-partials/my-dashboard/RoleManagement/RoleEnvironment.tsx
  lambda/app/src/controllers/roles.ts
  lambda/app/src/routes.ts
Labels: enhancement

#1268 fix: sso admin able to list composite roles and role users for any integration
  lambda/__tests__/22.sso-admin.test.ts
  lambda/__tests__/helpers/modules/roles.ts
  lambda/app/src/controllers/roles.ts
  lambda/app/src/controllers/user.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/src/routes.ts
Labels: bug

#1269 feat: include DIT contact in emails for non prod DC integration
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/digital-credential-info-contact.html
  lambda/shared/templates/helpers.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
Labels: enhancement

#1267 feat: typography styles
  app/components/CancelButton.tsx
  app/components/CenteredModal.tsx
  app/components/ControlledTable.tsx
  app/components/GenericModal.tsx
  app/components/InstallationModal.tsx
  app/components/InstallationPanel.tsx
  app/components/MiddleModal.tsx
  app/components/SubmittedStatusIndicator.tsx
  app/components/SurveyBox.tsx
  app/components/Table.tsx
  app/components/TableNew.tsx
  app/form-components/FieldInlineGrid.tsx
  app/form-components/FieldRequesterInfo.tsx
  app/form-components/FormButtons.tsx
  app/form-components/team-form/CreateTeamForm.tsx
  app/form-components/team-form/EditTeamNameForm.tsx
  app/interfaces/props.ts
  app/jest/layout.test.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/layout/BCSans.tsx
  app/layout/GoldNotificationModal.tsx
  app/layout/Layout.tsx
  app/layout/Navigation.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/MetadataEditModal.tsx
  app/page-partials/edit-request/CancelConfirmModal.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatusPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BceidStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BceidStatusPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/GithubStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/GithubStatusPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/RoleManagement/RoleEnvironment.tsx
  app/page-partials/my-dashboard/RoleManagement/index.tsx
  app/page-partials/my-dashboard/SecretsPanel.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  app/page-partials/my-dashboard/TeamList.tsx
  app/page-partials/my-dashboard/UserRoles.tsx
  app/page-partials/my-dashboard/users-roles/IdimLookup.tsx
  app/page-partials/new-request/SolutionNavigator.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/_app.tsx
  app/pages/admin-dashboard.tsx
  app/pages/admin-reports.tsx
  app/pages/index.tsx
  app/pages/terms-conditions.tsx
  app/pages/verify-user.tsx
  app/styles/globals.css
  app/styles/theme.ts
Labels: enhancement

#1270 fix: view only service accounts for sso-admin
  app/jest/ssoDashboard.test.tsx
  app/page-partials/my-dashboard/RoleManagement/RoleEnvironment.tsx
  app/pages/admin-dashboard.tsx
Labels: enhancement

#1271 feat: client id search
  app/jest/ssoDashboard.test.tsx
  app/pages/admin-dashboard.tsx
  lambda/__tests__/23.search-requests.test.ts
  lambda/__tests__/helpers/modules/integrations.ts
Labels: enhancement

#1272 feat: add token url to json for service accounts
  lambda/app/src/controllers/installation.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/keycloak/installation/index.ts
  lambda/app/src/keycloak/installation/oidc.ts
Labels: enhancement

#1273 chore: update the email content
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/team-invitation/team-invitation.html
Labels: enhancement

#1275 fix: bcsc
  .github/workflows/deploy-gh-pages-maintenance.yml
Labels: bug

#1276 chore: test env
  .github/workflows/terraform.yml
Labels: enhancement

#1277 build: test
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/terraform.yml
Labels: release:minor

#1278 fix: bcsc creation
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__mocks__/axios.ts
  lambda/app/src/bcsc/client.ts
Labels: bug

#1280 chore: bcsc prod feature flag
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/components/CenteredModal.tsx
  app/jest.setup.js
  app/jest/form.test.tsx
  app/next.config.js
  app/schemas/providers-gold.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
Labels: feature
