Repository bcgov/sso-requests, pull requests merged in 2024-01, with the labels that each got.

#1101 feat: removed dependency on terraform batch jobs to apply integrations to keycloak
  app/form-components/FormTemplate.tsx
  app/jest/ssoDashboard.test.tsx
  app/metadata/options.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/pages/admin-dashboard.tsx
  app/pages/my-dashboard/index.tsx
  app/pages/my-dashboard/integrations.tsx
  app/services/request.ts
  lambda/__tests__/01.auth.test.ts
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/04.requests-by-teams.test.ts
  lambda/__tests__/05.actions.test.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/09.emails-for-teams.test.ts
  lambda/__tests__/10.team-api-account.test.ts
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/__tests__/12.submit-survey.test.ts
  lambda/__tests__/13.profile.test.ts
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/roles.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/controllers/user.ts
  lambda/app/src/github.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/src/queries/roles.ts
  lambda/app/src/routes.ts
  lambda/db/src/migrations/2023.12.25T01.00.00.create-request-roles-table.ts
  lambda/db/src/migrations/2023.12.28T00.00.00.create-request-queues-table.ts
  lambda/db/src/umzug.ts
  lambda/shared/enums.ts
  lambda/shared/sequelize/models/RequestQueue.ts
  lambda/shared/sequelize/models/RequestRole.ts
  lambda/shared/sequelize/models/models.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/restore-integration/index.ts
  lambda/shared/templates/restore-integration/restore-integration.html
  localserver/.env.example
  localserver/nodemon-db.json
Labels: enhancement

#1102 fix: minor tweaks
  app/pages/admin-dashboard.tsx
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1104 feat: get rid of scheduler and actions lambdas
  .github/workflows/terraform.yml
  app/helpers/permissions.ts
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/MetadataEditModal.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  lambda/Makefile
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/04.requests-by-teams.test.ts
  lambda/__tests__/05.actions.test.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/09.emails-for-teams.test.ts
  lambda/__tests__/10.team-api-account.test.ts
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/__tests__/12.submit-survey.test.ts
  lambda/__tests__/13.profile.test.ts
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/__tests__/helpers/integration.ts
  lambda/__tests__/helpers/modules/common.ts
  lambda/__tests__/helpers/modules/surveys.ts
  lambda/__tests__/helpers/server.ts
  lambda/__tests__/jest.setup.js
  lambda/actions/Makefile
  lambda/actions/package.json
  lambda/actions/src/authenticate.ts
  lambda/actions/src/controllers/batch.ts
  lambda/actions/src/controllers/heartbeat.ts
  lambda/actions/src/github.ts
  lambda/actions/src/interfaces.ts
  lambda/actions/src/main.ts
  lambda/actions/src/routes.ts
  lambda/actions/tsconfig.json
  lambda/actions/yarn.lock
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/jest.config.js
  lambda/scheduler/Makefile
  lambda/scheduler/package.json
  lambda/scheduler/src/main.ts
  lambda/scheduler/tsconfig.json
  lambda/scheduler/yarn.lock
  lambda/shared/templates/processing-time.html
  lambda/tsconfig.json
  localserver/express-server.ts
  terraform/.terraform.lock.hcl
  terraform/api-gateway.tf
  terraform/cloudwatch.tf
  terraform/lambda-actions.tf
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-scheduler.tf
  terraform/variables.tf
Labels: enhancement

#1103 feat: run queued client requests on a schedule
  lambda/Makefile
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/__tests__/__mocks__/axios.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/request-queue/Makefile
  lambda/request-queue/README.md
  lambda/request-queue/package.json
  lambda/request-queue/src/main.ts
  lambda/request-queue/tsconfig.json
  lambda/request-queue/yarn.lock
  lambda/shared/interfaces.ts
  lambda/tsconfig.json
  terraform/cloudwatch.tf
  terraform/lambda-request-queue.tf
Labels: enhancement

#1105 feat: added numbering to emails
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/create-team-api-account-approved/index.ts
  lambda/shared/templates/create-team-api-account-submitted/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-submitted/index.ts
Labels: enhancement

#1106 fix: email configuration for request queue
  lambda/request-queue/Makefile
  lambda/request-queue/package.json
  lambda/request-queue/src/main.ts
  terraform/lambda-request-queue.tf
Labels: bug

#1107 chore: check kc running in gold before connecting
  lambda/app/src/keycloak/adminClient.ts
  lambda/request-queue/package.json
  lambda/request-queue/src/main.ts
  lambda/request-queue/tsconfig.json
  lambda/request-queue/yarn.lock
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-request-queue.tf
  terraform/variables.tf
Labels: enhancement

#1108 chore: wiki links
  app/components/InstallationPanel.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/team-form/TeamMembersForm.tsx
  app/jest/home.test.tsx
  app/jest/layout.test.tsx
  app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/my-dashboard/my-teams/cssApiAccount.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  app/layout/Layout.tsx
  app/page-partials/faq/FaqItems.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/index.tsx
  app/pages/my-dashboard/s2g.tsx
  app/schemas/providers-gold.ts
  app/schemas/providers.ts
  app/utils/constants.ts
Labels: enhancement

#1109 chore: update invite email
  app/form-components/team-form/TeamMembersForm.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/09.emails-for-teams.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/utils/helpers.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/team-invitation/index.ts
  lambda/shared/templates/team-invitation/team-invitation.html
Labels: enhancement

#1110 fix: copy
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/team-invitation/team-invitation.html
Labels: enhancement

#1111 feat: use local admin user and extend roles func to css api
  .github/workflows/k6-tests.yml
  .github/workflows/terraform.yml
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/05.requests-roles.test.ts
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/10.team-api-account.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/roles.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/keycloak/adminClient.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/src/queries/roles.ts
  lambda/css-api/src/services/role-service.ts
  lambda/db/src/migrations/2024.01.10T00.00.00.update-request-roles-table.ts
  lambda/db/src/umzug.ts
  lambda/package.json
  lambda/shared/sequelize/models/RequestRole.ts
  lambda/yarn.lock
  loadtests/lambdas/lambda.tf
  loadtests/lambdas/variables.tf
  localserver/.env.example
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-request-queue.tf
  terraform/variables-keycloak_v2.tf
Labels: enhancement

#1112 fix: disabling
  lambda/app/src/controllers/requests.ts
Labels: bug

#1113 feat: updated subject line for prod approval emails
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/prod-approved/index.ts
Labels: ui-improvement

#1114 chore: events for restoration
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/shared/enums.ts
Labels: enhancement

#1116 feat: create whats new section for homepage
  app/pages/index.tsx
  app/svg/StandardRealms.tsx
  app/svg/WhatsNewSVG.tsx
Labels: enhancement

#1117 feat: lambda function to monitor for applied requests missing from keycloak
  .github/workflows/terraform.yml
  lambda/Makefile
  lambda/__tests__/18.request-monitor.test.ts
  lambda/request-monitor/.env.example
  lambda/request-monitor/Makefile
  lambda/request-monitor/README.md
  lambda/request-monitor/package.json
  lambda/request-monitor/src/keycloak.ts
  lambda/request-monitor/src/main.ts
  lambda/request-monitor/tsconfig.json
  lambda/request-monitor/yarn.lock
  lambda/tsconfig.json
  terraform/cloudwatch.tf
  terraform/lambda-request-monitor.tf
  terraform/variables.tf
Labels: enhancement

#1119 chore: add links to what's new
  app/pages/index.tsx
Labels: enhancement

#1118 feat: minor tweaks to email and rc notification
  lambda/app/src/controllers/requests.ts
  lambda/request-monitor/Makefile
  lambda/request-monitor/package.json
  lambda/request-monitor/src/main.ts
  lambda/shared/templates/restore-integration/index.ts
  lambda/shared/templates/restore-integration/restore-integration.html
Labels: enhancement

#1120 fix: team api account delete and restore
  app/pages/admin-dashboard.tsx
  app/services/team.ts
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/queries/team.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/shared/enums.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/restore-team-api-account/index.ts
  lambda/shared/templates/restore-team-api-account/restore-team-api-account.html
Labels: bug

#1122 chore: change azure idir to idir with mfa
  app/helpers/meta.ts
  app/schemas/providers-gold.ts
Labels: enhancement

#1123 fix: keep the idps in sync at keycloak with css
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1124 chore: change docs link
  app/schemas/providers-gold.ts
Labels: bug

#1125 chore: release
  .github/workflows/terraform.yml
  app/helpers/meta.ts
  app/pages/admin-dashboard.tsx
  app/pages/index.tsx
  app/schemas/providers-gold.ts
  app/services/team.ts
  app/svg/StandardRealms.tsx
  app/svg/WhatsNewSVG.tsx
  lambda/Makefile
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/__tests__/18.request-monitor.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/team.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/team.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/request-monitor/.env.example
  lambda/request-monitor/Makefile
  lambda/request-monitor/README.md
  lambda/request-monitor/package.json
  lambda/request-monitor/src/keycloak.ts
  lambda/request-monitor/src/main.ts
  lambda/request-monitor/tsconfig.json
  lambda/request-monitor/yarn.lock
  lambda/shared/enums.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/restore-integration/index.ts
  lambda/shared/templates/restore-integration/restore-integration.html
  lambda/shared/templates/restore-team-api-account/index.ts
  lambda/shared/templates/restore-team-api-account/restore-team-api-account.html
  lambda/tsconfig.json
  terraform/cloudwatch.tf
  terraform/lambda-request-monitor.tf
  terraform/variables.tf
Labels: release:minor

#1126 fix: attach default scope common to saml integrations
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1127 fix: populate openid configuration from sso_url
  app/utils/provider.ts
Labels: bug

#1128 feat: testimonials
  app/components/Carousel.tsx
  app/components/Testimonial.tsx
  app/hooks/useWindowDimensions.tsx
  app/interfaces/Testimonial.ts
  app/pages/index.tsx
  app/utils/constants.ts
Labels: feature

#1129 chore: top quote on main page
  app/components/Carousel.tsx
  app/components/Testimonial.tsx
  app/interfaces/Testimonial.ts
  app/jest/home.test.tsx
  app/pages/index.tsx
  app/utils/constants.ts
Labels: enhancement
