Repository bcgov/sso-requests, pull requests merged in 2024-06, with the labels that each got.

#1214 feat: added bcsc idp and related form fields
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/BcscAttributesWidget.tsx
  app/form-components/widgets/BcscPrivacyZoneWidget.tsx
  app/helpers/integration.ts
  app/helpers/meta.ts
  app/interfaces/Request.ts
  app/interfaces/types.ts
  app/jest.setup.js
  app/jest/axe.test.tsx
  app/jest/form.test.tsx
  app/jest/request.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/next.config.js
  app/page-partials/admin-dashboard/AdminTabs/BcServicesCardTabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/pages/admin-dashboard.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/index.ts
  app/schemas/providers-gold.ts
  app/services/bc-services-card.ts
  app/styles/globals.css
  app/utils/constants.ts
  app/utils/helpers.tsx
  app/utils/validate.ts
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/controllers/bc-services-card.ts
  lambda/app/src/routes.ts
  lambda/shared/templates/apply-bc-services-card-bottom.html
  lambda/shared/templates/create-bc-services-card-bottom.html
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-bc-services-card-bottom.html
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
Labels: enhancement

#1216 feat: send bceid and bcsc emails to IDIM only in prod environment
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/BcscAttributesWidget.tsx
  app/form-components/widgets/BcscPrivacyZoneWidget.tsx
  app/helpers/integration.ts
  app/schemas-ui/ui-gold.ts
  app/services/bc-services-card.ts
  app/utils/constants.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/shared/local.ts
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/prod-approved/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-submitted/index.ts
Labels: enhancement

#1218 feat: add home page uri field to the request form for bcsc
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/schemas/environment-gold.ts
  app/utils/validate.ts
Labels: enhancement

#1220 feat: BCSC UI improvements #1
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/BcscAttributesWidget.tsx
  app/form-components/widgets/BcscPrivacyZoneWidget.tsx
  app/helpers/integration.ts
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/services/bc-services-card.ts
  app/utils/constants.ts
  app/utils/validate.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/shared/local.ts
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/prod-approved/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-submitted/index.ts
Labels: enhancement

#1221 fix: disable privacy zone and attributes for an BCSC integration after submit
  app/schemas-ui/ui-gold.ts
Labels: bug

#1222 fix: remove disable integration step before deletion
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/app/src/controllers/user.ts
Labels: bug

#1217 feat: bcsc backend
  .github/workflows/terraform.yml
  docker-compose.yml
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/clientScopes.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/constants.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.06.06T11.01.11.add-bcsc-table.ts
  lambda/db/src/umzug.ts
  lambda/request-queue/src/main.ts
  lambda/shared/sequelize/models/BcscClient.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/sequelize/models/models.ts
  localserver/.env.example
  terraform/lambda-app.tf
  terraform/lambda-request-queue.tf
  terraform/variables.tf
Labels: enhancement, feature

#1223 chore: deploy test
  .github/workflows/terraform.yml
  docker-compose.yml
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/controllers/user.ts
  lambda/app/src/keycloak/clientScopes.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/constants.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.06.06T11.01.11.add-bcsc-table.ts
  lambda/db/src/umzug.ts
  lambda/request-queue/src/main.ts
  lambda/shared/sequelize/models/BcscClient.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/sequelize/models/models.ts
  localserver/.env.example
  terraform/lambda-app.tf
  terraform/lambda-request-queue.tf
  terraform/variables.tf
Labels: enhancement

#1224 chore: deploy fix
  .github/workflows/terraform.yml
  lambda/app/src/controllers/bc-services-card.ts
Labels: bug

#1226 fix: transfer of ownership for orphan requests
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/app/src/controllers/user.ts
  lambda/shared/enums.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/orphan-integration/index.ts
  lambda/shared/templates/orphan-integration/orphan-integration.html
Labels: enhancement

#1225 chore: validations
  app/schemas/providers-gold.ts
Labels: bug

#1228 chore: deploy test
  app/schemas/providers-gold.ts
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/app/src/controllers/user.ts
  lambda/shared/enums.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/orphan-integration/index.ts
  lambda/shared/templates/orphan-integration/orphan-integration.html
Labels: enhancement

#1229 fix: scopes
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1230 feat: hide role management for bcsc only requests
  app/jest/integrationTabs.test.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
Labels: enhancement

#1231 fix: idp login flows and prod approval
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/integration.ts
  lambda/db/src/migrations/2024.06.21T11.35.24.add-bcsc-prod-approved.ts
  lambda/db/src/umzug.ts
  lambda/shared/sequelize/models/Request.ts
Labels: bug

#1234 feat: bcsc status panel for prod approvals
  app/form-components/FormTemplate.tsx
  app/helpers/integration.ts
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatusPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/utils/helpers.tsx
Labels: enhancement

#1233 chore: display name
  lambda/app/src/controllers/requests.ts
Labels: enhancement

#1235 feat: minor bug fixes for BCSC
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/BcscAttributesWidget.tsx
  app/helpers/integration.ts
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/BcServicesCardStatusPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/utils/helpers.tsx
  lambda/app/src/controllers/requests.ts
  lambda/shared/templates/orphan-integration/index.ts
Labels: bug

#1236 fix: address
  lambda/__tests__/20.bcsc.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/utils/helpers.ts
Labels: bug

#1237 chore: release
  lambda/__tests__/20.bcsc.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/utils/helpers.ts
Labels: enhancement

#1238 chore: tooltips
  app/schemas-ui/ui-gold.ts
  app/schemas/providers-gold.ts
Labels: enhancement

#1239 fix: email content for bcsc approved clients
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
Labels: bug

#1241 feat: ms lookup
  README.md
  app/page-partials/my-dashboard/UserRoles.tsx
  app/page-partials/my-dashboard/users-roles/IdimLookup.tsx
  app/services/bceid-webservice.ts
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/19.idir-search.test.ts
  lambda/app/src/bceid-webservice-proxy/idir.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/ms-graph/idir.ts
  lambda/app/src/routes.ts
  lambda/shared/interfaces.ts
Labels: enhancement

#1242 chore: testid
  app/page-partials/my-dashboard/UserRoles.tsx
Labels: enhancement
