Repository bcgov/sso-requests, pull requests merged in 2024-10, with the labels that each got.

#1315 fix: display role info on layout changes
  app/layout/Layout.tsx
Labels: bug

#1316 fix: verify if client roles exist
  app/layout/Layout.tsx
Labels: bug

#1317 feat: update nodejs to 20 and use new keycloak lib
  .tool-versions
  app/package.json
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/services/axios.ts
  app/services/grafana.ts
  app/yarn.lock
  docs/developer-guide.md
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/controllers/user.ts
  lambda/app/src/keycloak/adminClient.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/installation/oidc.ts
  lambda/app/src/keycloak/installation/saml.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/yarn.lock
  lambda/css-api/yarn.lock
  lambda/package-lock.json
  lambda/package.json
  lambda/request-monitor/package-lock.json
  lambda/request-monitor/package.json
  lambda/request-monitor/src/keycloak.ts
  lambda/request-monitor/yarn.lock
  lambda/request-queue/yarn.lock
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  loadtests/lambdas/lambda.tf
  localserver/package.json
  localserver/yarn.lock
  role-migration/.tool-versions
  role-migration/package-lock.json
  role-migration/package.json
  role-migration/yarn.lock
  terraform/env-resources.tf_dev
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-db.tf
  terraform/lambda-request-monitor.tf
  terraform/lambda-request-queue.tf
  yarn.lock
Labels: enhancement

#1318 feat: release to test
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .tool-versions
  app/interfaces/props.ts
  app/jest/idp-approvals.test.tsx
  app/jest/my-dashboard/my-teams/helpers.tsx
  app/jest/ssoDashboard.test.tsx
  app/layout/Layout.tsx
  app/package.json
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/pages/admin-dashboard.tsx
  app/pages/admin-reports.tsx
  app/services/axios.ts
  app/services/grafana.ts
  app/utils/helpers.tsx
  app/yarn.lock
  docs/developer-guide.md
  lambda/__tests__/25.idp-approver.test.ts
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/controllers/events.ts
  lambda/app/src/controllers/user.ts
  lambda/app/src/keycloak/adminClient.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/installation/oidc.ts
  lambda/app/src/keycloak/installation/saml.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/app/yarn.lock
  lambda/css-api/yarn.lock
  lambda/package-lock.json
  lambda/package.json
  lambda/request-monitor/package-lock.json
  lambda/request-monitor/package.json
  lambda/request-monitor/src/keycloak.ts
  lambda/request-monitor/yarn.lock
  lambda/request-queue/yarn.lock
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  loadtests/lambdas/lambda.tf
  localserver/package.json
  localserver/yarn.lock
  role-migration/.tool-versions
  role-migration/package-lock.json
  role-migration/package.json
  role-migration/yarn.lock
  terraform/env-resources.tf_dev
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-db.tf
  terraform/lambda-request-monitor.tf
  terraform/lambda-request-queue.tf
  yarn.lock
Labels: ignore-for-release

#1319 chore: release
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .tool-versions
  app/interfaces/props.ts
  app/jest/idp-approvals.test.tsx
  app/jest/my-dashboard/my-teams/helpers.tsx
  app/jest/ssoDashboard.test.tsx
  app/layout/Layout.tsx
  app/package.json
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/pages/admin-dashboard.tsx
  app/pages/admin-reports.tsx
  app/services/axios.ts
  app/services/grafana.ts
  app/utils/helpers.tsx
  app/yarn.lock
  docs/developer-guide.md
  lambda/__tests__/25.idp-approver.test.ts
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/controllers/events.ts
  lambda/app/src/controllers/user.ts
  lambda/app/src/keycloak/adminClient.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/installation/oidc.ts
  lambda/app/src/keycloak/installation/saml.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/keycloak/users.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/app/yarn.lock
  lambda/css-api/yarn.lock
  lambda/package-lock.json
  lambda/package.json
  lambda/request-monitor/package-lock.json
  lambda/request-monitor/package.json
  lambda/request-monitor/src/keycloak.ts
  lambda/request-monitor/yarn.lock
  lambda/request-queue/yarn.lock
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  loadtests/lambdas/lambda.tf
  localserver/package.json
  localserver/yarn.lock
  role-migration/.tool-versions
  role-migration/package-lock.json
  role-migration/package.json
  role-migration/yarn.lock
  terraform/env-resources.tf_dev
  terraform/lambda-app.tf
  terraform/lambda-css-api.tf
  terraform/lambda-db.tf
  terraform/lambda-request-monitor.tf
  terraform/lambda-request-queue.tf
  yarn.lock
Labels: release:minor

#1320 chore: update the grafana filesystem access policies
  terraform/ecs.tf
Labels: enhancement

#1321 feat: download logs has rate limit activated
  app/cypress.config.ts
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/services/grafana.ts
  lambda/__tests__/01.auth.test.ts
  lambda/__tests__/02.users-and-teams.test.ts
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/04.requests-by-teams.test.ts
  lambda/__tests__/05.requests-roles.test.ts
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/09.emails-for-teams.test.ts
  lambda/__tests__/10.team-api-account.test.ts
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/__tests__/12.submit-survey.test.ts
  lambda/__tests__/13.profile.test.ts
  lambda/__tests__/14.digital-credential.test.ts
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/16.integration-metrics.test.ts
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/__tests__/18.request-monitor.test.ts
  lambda/__tests__/19.idir-search.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/22.sso-admin.test.ts
  lambda/__tests__/23.search-requests.test.ts
  lambda/__tests__/25.idp-approver.test.ts
  lambda/__tests__/helpers/common-mocks.js
  lambda/__tests__/jest.setup.js
  lambda/app/package.json
  lambda/app/src/routes.ts
  lambda/app/src/utils/rate-limiters.ts
  lambda/app/yarn.lock
  lambda/yarn.lock
  localserver/yarn.lock
Labels: enhancement

#1322 fix: enable ssl for production env
  lambda/app/src/utils/rate-limiters.ts
  lambda/shared/sequelize/config/config.ts
  localserver/yarn.lock
Labels: ignore-for-release

#1323 fix: fetch token-url instead of auth-server-url
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
Labels: bug

#1324 feat: use redis store as cache in prod env
  .github/workflows/terraform.yml
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/helpers/common-mocks.js
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/routes.ts
  lambda/app/src/utils/rate-limiters.ts
  lambda/app/yarn.lock
  lambda/css-api/yarn.lock
  lambda/request-queue/package-lock.json
  lambda/request-queue/yarn.lock
  package.json
  terraform/.terraform.lock.hcl
  terraform/alb.tf
  terraform/api-gateway-grafana.tf
  terraform/ecs.tf
  terraform/efs.tf
  terraform/lambda-app.tf
  terraform/main.tf
  terraform/nlb.tf
  terraform/roles.tf
  terraform/variables-ecs.tf
  terraform/variables-grafana.tf
Labels: enhancement

#1325 fix: updated token url key name (#1323)
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
Labels: enhancement

#1326 chore: release
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
Labels: release:patch

#1328 feat: fetch redis host from tf deploy
  .github/workflows/terraform.yml
  terraform/api-gateway-grafana.tf
  terraform/lambda-app.tf
  terraform/variables-ecs.tf
Labels: enhancement

#1329 feat: optimize cpu and memory for grafana and redis
  .github/workflows/terraform.yml
  terraform/ecs.tf
Labels: enhancement

#1330 chore: disable archived approval
  app/jest/ssoDashboard.test.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
Labels: bug

#1332 chore: remove cypress cloud runs
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e.yaml
Labels: enhancement

#1333 fix: actions
  .github/workflows/e2e.yaml
Labels: bug

#1334 chore: disable videos
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e.yaml
Labels: enhancement
