Repository bcgov/sso-requests, pull requests merged in 2024-04, with the labels that each got.

#1177 feat: restore integration
  .github/workflows/e2e.yaml
  app/components/CenteredModal.tsx
  app/jest/ssoDashboard.test.tsx
  app/pages/admin-dashboard.tsx
  app/services/request.ts
  docker-compose.yml
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/app/src/bceid-webservice-proxy/idir.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/routes.ts
Labels: enhancement

#1178 chore: prompt text
  app/pages/admin-dashboard.tsx
Labels: enhancement

#1179 feat: client error handling update
  app/components/ActionButtons.tsx
  app/components/InstallationPanel.tsx
  app/components/TableNew.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/team-form/CreateTeamForm.tsx
  app/form-components/team-form/TeamMembersForm.tsx
  app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
  app/jest/my-dashboard/my-projects/assignUsersToRoles.test.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/MetricsPanel.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/Messages.tsx
  app/page-partials/my-dashboard/RoleManagement/CreateRoleContent.tsx
  app/page-partials/my-dashboard/RoleManagement/RoleEnvironment.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/ServiceAccountsList.tsx
  app/page-partials/my-dashboard/TeamInfoTabs/index.tsx
  app/page-partials/my-dashboard/UserRoles.tsx
  app/pages/admin-dashboard.tsx
  app/pages/admin-reports.tsx
  app/services/axios.ts
  app/services/report.ts
Labels: enhancement

#1180 chore: error handling
  app/components/GithubDiscussions.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/team-form/EditTeamNameForm.tsx
  app/form-components/team-form/TeamMembersForm.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/my-dashboard/TeamList.tsx
  app/page-partials/my-dashboard/UserRoles.tsx
  app/page-partials/my-dashboard/users-roles/IdimLookup.tsx
  app/pages/admin-dashboard.tsx
  app/utils/users.ts
Labels: enhancement

#1184 chore: update migrator
  .github/workflows/e2e.yaml
  local/terraform/main.tf
Labels: bug

#1183 chore: add a flag for first stage of form
  app/form-components/FormTemplate.tsx
Labels: enhancement

#1182 feat: added switch to enable/disable offline access for new clients
  app/form-components/widgets/SwitchWidget.tsx
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/package.json
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/yarn.lock
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.04.18T00.00.00.add-flag-offline-access-enabled.ts
  lambda/db/src/umzug.ts
  lambda/shared/sequelize/models/Request.ts
Labels: enhancement

#1185 fix: bulk update offline access enabled to true
  lambda/db/src/migrations/2024.04.23T00.00.00.add-flag-offline-access-enabled.ts
  lambda/db/src/umzug.ts
Labels: bug

#1186 fix: ignore offline access enabled flag for saml integrations
  app/jest/samples/integrations.ts
  app/schemas-ui/ui-gold.ts
  lambda/app/src/utils/helpers.ts
Labels: bug

#1187 chore: release
  .github/workflows/e2e.yaml
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/SwitchWidget.tsx
  app/interfaces/Request.ts
  app/jest/form.test.tsx
  app/jest/samples/integrations.ts
  app/package.json
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/yarn.lock
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.04.23T00.00.00.add-flag-offline-access-enabled.ts
  lambda/db/src/umzug.ts
  lambda/shared/sequelize/models/Request.ts
  local/terraform/main.tf
Labels: release:minor

#1188 chore: client stopper
  lambda/app/src/controllers/requests.ts
Labels: enhancement
