Repository bcgov/sso-requests, pull requests merged in 2024-05, with the labels that each got.

#1189 chore: update emails
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/shared/local.ts
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/index.ts
Labels: enhancement

#1190 chore: emails
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
Labels: enhancement

#1191 chore: disable dc for saml
  app/form-components/FormTemplate.tsx
  app/jest.setup.js
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  app/utils/validate.ts
  lambda/__tests__/14.verifiable-credential.test.ts
Labels: bug

#1192 feat: confirm deletion
  app/components/ActionButtons.tsx
  app/components/CenteredModal.tsx
  app/components/DeleteModal.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-teams/integrations.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/pages/admin-dashboard.tsx
Labels: feature

#1193 fix: loader
  app/components/DeleteModal.tsx
Labels: bug

#1194 chore: deletion label
  app/components/DeleteModal.tsx
Labels: enhancement

#1195 chore: trim project name
  app/components/DeleteModal.tsx
Labels: enhancement

#1196 chore: enable dc
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
Labels: feature

#1200 feat: allow only fully qualified domains in redirect URI for dev and test
  app/jest/form.test.tsx
  app/jest/helpers.test.ts
  app/package.json
  app/utils/validate.ts
  app/yarn.lock
  terraform/ecs.tf
  terraform/roles.tf
Labels: enhancement

#1203 chore: release
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/components/ActionButtons.tsx
  app/components/CenteredModal.tsx
  app/components/DeleteModal.tsx
  app/form-components/ArrayFieldTemplate.tsx
  app/form-components/FormTemplate.tsx
  app/jest.setup.js
  app/jest/form.test.tsx
  app/jest/helpers.test.ts
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-teams/integrations.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/package.json
  app/pages/admin-dashboard.tsx
  app/schemas-ui/ui-gold.ts
  app/utils/validate.ts
  app/yarn.lock
  lambda/__tests__/14.verifiable-credential.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/adminClient.ts
  lambda/css-api/src/swagger.js
  lambda/shared/local.ts
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-submitted/index.ts
  terraform/ecs.tf
  terraform/env-resources.tf_test
  terraform/roles.tf
Labels: release:minor

#1205 fix: allow * in domain and path for dev and test
  app/form-components/ArrayFieldTemplate.tsx
  app/jest/helpers.test.ts
  app/utils/validate.ts
Labels: enhancement

#1206 chore: Allow * in domain and paths for redirect URIs
  .github/workflows/k6-tests.yml
  app/form-components/ArrayFieldTemplate.tsx
  app/jest/helpers.test.ts
  app/utils/validate.ts
  lambda/css-api/k6-tests/.cicd/init.sql
Labels: enhancement

#1208 chore: redirect uris
  app/jest/form.test.tsx
  app/jest/helpers.test.ts
  app/utils/validate.ts
Labels: bug

#1209 fix: text
  app/form-components/ArrayFieldTemplate.tsx
Labels: bug

#1211 chore: release
  app/form-components/ArrayFieldTemplate.tsx
  app/jest/form.test.tsx
  app/jest/helpers.test.ts
  app/utils/validate.ts
Labels: enhancement, release:patch

#1212 chore: terms and condition text
  app/page-partials/terms-conditions/Content.tsx
Labels: enhancement

#1213 feat: logs ui
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
Labels: enhancement
