Repository bcgov/sso-requests, pull requests merged in 2024-09, with the labels that each got.

#1281 fix: able to list only bc services requests by admin
  app/interfaces/Request.ts
  app/utils/helpers.tsx
Labels: bug

#1282 chore: bcsc feature flag
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
Labels: enhancement

#1283 chore: release test
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/interfaces/Request.ts
  app/utils/helpers.tsx
Labels: enhancement

#1284 chore: release prod
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/components/CenteredModal.tsx
  app/interfaces/Request.ts
  app/jest.setup.js
  app/jest/form.test.tsx
  app/next.config.js
  app/schemas/providers-gold.ts
  app/utils/helpers.tsx
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__mocks__/axios.ts
  lambda/app/src/bcsc/client.ts
Labels: release:minor

#1285 fix: privacy zone uris
  app/components/RequestPreview.tsx
  app/form-components/FieldReviewAndSubmit.tsx
  app/jest/ssoDashboard.test.tsx
  app/page-partials/admin-dashboard/AdminRequestPanel.tsx
  app/schemas/providers-gold.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/bc-services-card.ts
Labels: bug

#1286 feat: enable bcsc for saml integrations
  app/form-components/FormTemplate.tsx
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/clientScopes.ts
  lambda/app/src/keycloak/integration.ts
Labels: enhancement

#1287 feat: update bcsc IDP scopes if attributes are updated
  app/services/bc-services-card.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/utils/helpers.ts
Labels: bug

#1289 feat: remove approval process for DC prod integrations
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/page-partials/admin-dashboard/AdminTabs/DigitalCredentialTabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/utils/helpers.tsx
  lambda/__tests__/14.digital-credential.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/controllers/requests.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.09.16T00.00.00.remove-vc-approved.ts
  lambda/db/src/umzug.ts
  lambda/shared/local.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
Labels: enhancement

#1288 feat: role message
  app/form-components/widgets/TooltipCheckboxesWidget.tsx
  app/schemas/providers-gold.ts
  app/styles/globals.css
Labels: enhancement

#1290 chore: bcsc prod available
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/schemas/providers-gold.ts
Labels: enhancement

#1291 chore: release preview
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/components/RequestPreview.tsx
  app/form-components/FieldReviewAndSubmit.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/TooltipCheckboxesWidget.tsx
  app/jest/form.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/page-partials/admin-dashboard/AdminRequestPanel.tsx
  app/page-partials/admin-dashboard/AdminTabs/DigitalCredentialTabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/schemas/providers-gold.ts
  app/services/bc-services-card.ts
  app/styles/globals.css
  app/utils/helpers.tsx
  lambda/__tests__/14.digital-credential.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/bc-services-card.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/clientScopes.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.09.16T00.00.00.remove-vc-approved.ts
  lambda/db/src/umzug.ts
  lambda/shared/local.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
Labels: enhancement

#1292 fix: mergefix main
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/components/RequestPreview.tsx
  app/form-components/FieldReviewAndSubmit.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/TooltipCheckboxesWidget.tsx
  app/jest/form.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/page-partials/admin-dashboard/AdminRequestPanel.tsx
  app/page-partials/admin-dashboard/AdminTabs/DigitalCredentialTabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/DigitalCredentialStatus.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/shared.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/schemas/providers-gold.ts
  app/services/bc-services-card.ts
  app/styles/globals.css
  app/utils/helpers.tsx
  lambda/__tests__/14.digital-credential.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/bc-services-card.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/clientScopes.ts
  lambda/app/src/keycloak/idp.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/utils/helpers.ts
  lambda/db/src/migrations/2024.09.16T00.00.00.remove-vc-approved.ts
  lambda/db/src/umzug.ts
  lambda/shared/local.ts
  lambda/shared/sequelize/models/Request.ts
  lambda/shared/templates/create-integration-applied/create-integration-applied.html
  lambda/shared/templates/create-integration-applied/index.ts
  lambda/shared/templates/create-integration-submitted/create-integration-submitted.html
  lambda/shared/templates/create-integration-submitted/index.ts
  lambda/shared/templates/delete-integration-submitted/index.ts
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
Labels: release:minor

#1293 fix: terraform var
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: bug

#1294 chore: add flag to tf vars
  .github/workflows/terraform.yml
Labels: bug

#1296 chore: revert flag
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
Labels: bug

#1297 chore: merge
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: enhancement

#1298 chore: revert bcsc flag
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: bug, release:patch

#1299 fix: bcsc-scope
  lambda/__tests__/20.bcsc.test.ts
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1302 chore: switch flag
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
Labels: enhancement

#1303 chore: release test
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  .gitignore
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/25.idp-approver.test.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/__tests__/jest.setup.js
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/__tests__/processRequest.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/request.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/app/yarn.lock
  lambda/css-api/package-lock.json
  lambda/css-api/package.json
  lambda/css-api/yarn.lock
  lambda/db/package-lock.json
  lambda/db/yarn.lock
  lambda/package-lock.json
  lambda/package.json
  lambda/request-monitor/package-lock.json
  lambda/request-monitor/yarn.lock
  lambda/request-queue/package-lock.json
  lambda/request-queue/yarn.lock
  lambda/shared/package-lock.json
  lambda/siteminder-tests-scheduler/package-lock.json
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  localserver/yarn.lock
  role-migration/package-lock.json
  role-migration/yarn.lock
Labels: release:minor

#1304 chore: release production
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  .gitignore
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/25.idp-approver.test.ts
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/__tests__/jest.setup.js
  lambda/app/package-lock.json
  lambda/app/package.json
  lambda/app/src/__tests__/processRequest.test.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/request.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/app/yarn.lock
  lambda/css-api/package-lock.json
  lambda/css-api/package.json
  lambda/css-api/yarn.lock
  lambda/db/package-lock.json
  lambda/db/yarn.lock
  lambda/package-lock.json
  lambda/package.json
  lambda/request-monitor/package-lock.json
  lambda/request-monitor/yarn.lock
  lambda/request-queue/package-lock.json
  lambda/request-queue/yarn.lock
  lambda/shared/package-lock.json
  lambda/siteminder-tests-scheduler/package-lock.json
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  localserver/yarn.lock
  role-migration/package-lock.json
  role-migration/yarn.lock
Labels: release:minor

#1301 chore: e2e test suite
  .dockerignore
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e.yaml
  .gitignore
  app/README.md
  app/components/Table.tsx
  app/cypress.config.ts
  app/cypress.json
  app/cypress/appActions/Request.ts
  app/cypress/appActions/Team.ts
  app/cypress/appActions/Utilities.ts
  app/cypress/e2e/README.md
  app/cypress/e2e/ci/integrations-crud.cy.ts
  app/cypress/e2e/ci/smoke-10-brokenlinks.cy.ts
  app/cypress/e2e/ci/team-tests.cy.ts
  app/cypress/e2e/external/idpstopper-010-test7-8.cy.ts
  app/cypress/e2e/external/idpstopper-020-test11.cy.ts
  app/cypress/e2e/external/idpstopper-040-ssosession.cy.ts
  app/cypress/e2e/external/idpstopper-050-login-page-name-capitalization.cy.ts
  app/cypress/e2e/external/integration-990-deleteAllIntegrations.cy.ts
  app/cypress/e2e/external/integration-roles.cy.ts
  app/cypress/e2e/external/search-users.cy.ts
  app/cypress/e2e/external/sso-010-createIntegration.cy.ts
  app/cypress/e2e/external/sso-020-sessions.cy.ts
  app/cypress/e2e/external/sso-090-deleteIntegration.cy.ts
  app/cypress/fixtures/capitalization-fixtures.json
  app/cypress/fixtures/github-bcgov-idp.json
  app/cypress/fixtures/githubbcgovtest.json
  app/cypress/fixtures/idim-search.json
  app/cypress/fixtures/idpstopper.json
  app/cypress/fixtures/idpstopper11.json
  app/cypress/fixtures/idpstoppersaml.json
  app/cypress/fixtures/requests-roles.json
  app/cypress/fixtures/requests.json
  app/cypress/fixtures/rolesusers.json
  app/cypress/fixtures/search-test-integration.json
  app/cypress/fixtures/sso-requests.json
  app/cypress/fixtures/sso-test.json
  app/cypress/fixtures/standalone-requests.json
  app/cypress/fixtures/teams.json
  app/cypress/integration/user-workflow.spec.js
  app/cypress/pageObjects/README.md
  app/cypress/pageObjects/dashboardPage.ts
  app/cypress/pageObjects/homePage.ts
  app/cypress/pageObjects/loginProxy.ts
  app/cypress/pageObjects/playgroundPage.ts
  app/cypress/pageObjects/requestPage.ts
  app/cypress/pageObjects/teamPage.ts
  app/cypress/support/commands.ts
  app/cypress/support/e2e.ts
  app/cypress/support/global.d.ts
  app/cypress/support/integration.ts
  app/package.json
  app/tsconfig.json
  app/yarn.lock
  docker-compose.yml
Labels: enhancement

#1305 fix: email for pz
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
  app/helpers/integration.ts
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/helpers.ts
  lambda/shared/templates/index.ts
  lambda/shared/templates/integration-detail.html
Labels: bug

#1306 chore: cron
  .github/workflows/cypress.yml
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e-smoke-test.yaml
Labels: enhancement

#1310 chore: bcsc
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/terraform.yml
Labels: feature

#1311 chore: release test
  .github/workflows/cypress.yml
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e-smoke-test.yaml
  .github/workflows/terraform.yml
Labels: enhancement

#1312 chore: release
  .github/workflows/cypress.yml
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/e2e-keycloak.yaml
  .github/workflows/e2e-smoke-test.yaml
  .github/workflows/terraform.yml
Labels: release:minor

#1309 feat: IDP approver roles for BCeID, GitHub and BC Services Card
  app/interfaces/props.ts
  app/jest/idp-approvals.test.tsx
  app/jest/my-dashboard/my-teams/helpers.tsx
  app/jest/ssoDashboard.test.tsx
  app/layout/Layout.tsx
  app/page-partials/admin-dashboard/AdminTabs/TabContent.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
  app/pages/admin-dashboard.tsx
  app/pages/admin-reports.tsx
  app/utils/helpers.tsx
  lambda/__tests__/25.idp-approver.test.ts
  lambda/app/src/controllers/events.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/helpers.ts
  lambda/app/yarn.lock
Labels: enhancement

#1313 chore: set action version
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
Labels: bug

#1314 fix: Only user with IDP approver role can approve
  app/jest/idp-approvals.test.tsx
  app/page-partials/admin-dashboard/AdminTabs/index.tsx
Labels: enhancement
