Repository bcgov/sso-requests, pull requests merged in 2024-02, with the labels that each got.

#1130 feat: keep existing composite roles
  lambda/css-api/src/services/role-service.ts
Labels: bug

#1134 fix: push trigger
  .github/workflows/e2e-smoke-test.yaml
Labels: miscellaneous

#1136 feat: fixes to run conditions for e2e
  .github/workflows/e2e-smoke-test.yaml
Labels: miscellaneous

#1137 feat: docker compose for local development environment and automation e2e
  .dockerignore
  Dockerfile
  Dockerfile.tf-modules
  app/next.config.js
  docker-compose.yml
  docs/developer-guide.md
  lambda/app/src/keycloak/adminClient.ts
  lambda/request-monitor/src/main.ts
  local/database-init.sql
  local/terraform/main.tf
  local/terraform/provider.tf
  local/terraform/variables.tf
  local/tf-migration-entrypoint.sh
  localserver/nodemon-db.json
Labels: enhancement

#1138 feat: update kc url for tf kc provider 4.4.0
  local/terraform/provider.tf
Labels: miscellaneous

#1139 chore: modify the docker-compose file to work with ubuntu
  Dockerfile.tf-modules
  docker-compose.yml
  docs/developer-guide.md
Labels: enhancement

#1145 fix: saml - override roles attribute instead of adding new
  app/form-components/FormTemplate.tsx
  app/schemas/providers-gold.ts
Labels: bug

#1144 chore: url
  app/form-components/team-form/TeamMembersForm.tsx
  app/jest/home.test.tsx
  app/jest/layout.test.tsx
  app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  app/layout/Layout.tsx
  app/page-partials/faq/FaqItems.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/index.tsx
  app/pages/my-dashboard/s2g.tsx
  app/schemas/providers-gold.ts
  app/utils/constants.ts
Labels: enhancement

#1146 fix(delete-role): update sql query to fetch composite roles by integration
  lambda/app/src/queries/roles.ts
Labels: bug

#1147 chore: release
  .dockerignore
  .github/workflows/e2e-smoke-test.yaml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.tf-modules
  README.md
  app/components/Carousel.tsx
  app/components/Testimonial.tsx
  app/form-components/FormTemplate.tsx
  app/form-components/team-form/TeamMembersForm.tsx
  app/hooks/useWindowDimensions.tsx
  app/interfaces/Testimonial.ts
  app/jest.config.js
  app/jest/home.test.tsx
  app/jest/layout.test.tsx
  app/jest/my-dashboard/my-projects/assignServiceAccountsToRoles.test.tsx
  app/jest/my-dashboard/my-projects/integrationList.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  app/layout/Layout.tsx
  app/next.config.js
  app/page-partials/faq/FaqItems.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/page-partials/my-dashboard/IntegrationList.tsx
  app/page-partials/my-dashboard/ServiceAccountRoles.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/index.tsx
  app/pages/my-dashboard/s2g.tsx
  app/schemas/providers-gold.ts
  app/utils/constants.ts
  app/utils/provider.ts
  codecov.yml
  docker-compose.yml
  docs/developer-guide.md
  lambda/app/src/keycloak/adminClient.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/roles.ts
  lambda/css-api/src/services/role-service.ts
  lambda/jest.config.js
  lambda/request-monitor/src/main.ts
  local/database-init.sql
  local/terraform/main.tf
  local/terraform/provider.tf
  local/terraform/variables.tf
  local/tf-migration-entrypoint.sh
  localserver/nodemon-db.json
Labels: release:minor

#1149 fix: use saml config for the add role attr mappers
  lambda/app/src/keycloak/integration.ts
Labels: bug

#1150 fix: disable additional role attribute mapper for SAML
  app/schemas/providers-gold.ts
Labels: bug

#1151 chore: patch
  app/schemas/providers-gold.ts
  lambda/app/src/keycloak/integration.ts
Labels: release:patch

#1140 feat: logs
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/services/grafana.ts
  lambda/__tests__/15.sso-logs.test.ts
  lambda/app/src/controllers/logs.ts
  lambda/app/src/routes.ts
  lambda/shared/enums.ts
Labels: feature

#1152 chore: dev limit
  lambda/app/src/controllers/logs.ts
Labels: bug

#1153 feat: download events
  app/pages/admin-reports.tsx
  lambda/app/src/controllers/reports.ts
Labels: bug

#1154 chore: abort query
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
Labels: enhancement

#1155 chore: text
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  lambda/app/src/controllers/logs.ts
Labels: enhancement

#1156 feat: use docker compose to generate dev test and prod locally
  docker-compose.yml
  docs/developer-guide.md
  local/database-init.sql
  local/tf-migration-entrypoint.sh
Labels: enhancement

#1158 chore: client session form validations
  app/form-components/team-form/TeamMembersForm.tsx
  app/form-components/widgets/MinutesToSeconds.tsx
  app/jest/form.test.tsx
  app/jest/samples/integrations.ts
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/utils/constants.ts
  app/utils/validate.ts
Labels: enhancement

#1159 chore: doc update end to end test
  docs/developer-guide.md
Labels: enhancement

#1160 chore: cypress update
  .dockerignore
  app/package.json
  app/pages/_app.tsx
  docker-compose.yml
  lambda/app/src/bceid-webservice-proxy/idir.ts
  lambda/app/src/utils/constants.ts
Labels: enhancement

#1161 chore: release
  .dockerignore
  .github/workflows/terraform.yml
  app/form-components/team-form/TeamMembersForm.tsx
  app/form-components/widgets/MinutesToSeconds.tsx
  app/jest/form.test.tsx
  app/jest/my-dashboard/my-teams/members.test.tsx
  app/jest/my-dashboard/my-teams/teamList.test.tsx
  app/jest/samples/integrations.ts
  app/package.json
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  app/page-partials/my-dashboard/IntegrationInfoTabs/index.tsx
  app/pages/_app.tsx
  app/pages/admin-reports.tsx
  app/schemas-ui/ui-gold.ts
  app/schemas/environment-gold.ts
  app/services/grafana.ts
  app/services/user.ts
  app/types/users.ts
  app/utils/constants.ts
  app/utils/validate.ts
  app/yarn.lock
  docker-compose.yml
  docs/developer-guide.md
  lambda/__tests__/15.sso-logs.test.ts
  lambda/__tests__/19.idir-search.test.ts
  lambda/__tests__/helpers/modules/users.ts
  lambda/app/package.json
  lambda/app/src/bceid-webservice-proxy/idir.ts
  lambda/app/src/controllers/logs.ts
  lambda/app/src/controllers/reports.ts
  lambda/app/src/routes.ts
  lambda/app/src/utils/constants.ts
  lambda/app/yarn.lock
  lambda/shared/enums.ts
  local/database-init.sql
  local/tf-migration-entrypoint.sh
  localserver/.env.example
  terraform/lambda-app.tf
  terraform/variables.tf
Labels: release:minor
