Repository bcgov/sso-requests, pull requests merged in 2024-12, with the labels that each got.

#1344 feat: refactored CSS API for improved performance
  lambda/__tests__/10.team-api-account.test.ts
  lambda/app/package-lock.json
  lambda/app/src/controllers/roles.ts
  lambda/app/src/queries/roles.ts
  lambda/app/yarn.lock
  lambda/css-api/k6-tests/cleanup.sh
  lambda/css-api/k6-tests/load-tests.js
  lambda/css-api/k6-tests/smoke-tests/modules/user-role-mappings.js
  lambda/css-api/package-lock.json
  lambda/css-api/src/authenticate.ts
  lambda/css-api/src/controllers/integration-controller.ts
  lambda/css-api/src/controllers/role-controller.ts
  lambda/css-api/src/controllers/user-controller.ts
  lambda/css-api/src/controllers/user-role-mapping-controller.ts
  lambda/css-api/src/routes.ts
  lambda/css-api/src/services/keycloak-service.ts
  lambda/css-api/src/services/role-service.ts
  lambda/css-api/src/services/user-role-mapping-service.ts
  lambda/css-api/src/services/user-service.ts
  lambda/css-api/src/types.ts
  lambda/css-api/src/util.ts
  lambda/request-monitor/yarn.lock
  lambda/request-queue/yarn.lock
  lambda/shared/sequelize/config/config.ts
  lambda/siteminder-tests-scheduler/yarn.lock
Labels: enhancement

#1345 fix: user deletion
  Dockerfile.tf-modules
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/11.remove-inactive-users.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/controllers/user.ts
  lambda/app/src/queries/team.ts
  lambda/shared/templates/delete-inactive-idir-users/delete-inactive-idir-users.html
Labels: bug

#1346 chore: backoff limit
  app/page-partials/my-dashboard/IntegrationInfoTabs/LogsPanel.tsx
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/__tests__/helpers/modules/integrations.ts
  lambda/db/src/migrations/2024.12.03T10.55.55.request-queue-attempts-column.ts
  lambda/db/src/umzug.ts
  lambda/request-queue/package.json
  lambda/request-queue/src/main.ts
  lambda/shared/sequelize/models/RequestQueue.ts
  terraform/lambda-request-queue.tf
Labels: enhancement

#1347 fix: sequalize connections
  lambda/jest.config.js
  lambda/request-queue/src/db.ts
  lambda/request-queue/src/main.ts
Labels: bug

#1349 chore: connection limit
  lambda/__tests__/17.run-queued-requests.test.ts
  lambda/jest.config.js
  lambda/request-queue/src/db.ts
  lambda/request-queue/src/main.ts
  terraform/lambda-request-queue.tf
Labels: bug

#1352 chore: set archived status default to active only
  app/components/Table.tsx
  app/jest/ssoDashboard.test.tsx
  app/pages/admin-dashboard.tsx
Labels: enhancement

#1353 chore: old module
  terraform/env-resources.tf_prod
Labels: bug

#1354 feat: format client name and jwks uri for bcsc integrations
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
Labels: bug

#1355 chore: mailing list
  app/page-partials/terms-conditions/Content.tsx
  app/pages/index.tsx
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/sso-updates-mailing-list-message.html
Labels: bug

#1356 feat: update client name for BCSC integrations
  lambda/app/src/controllers/requests.ts
Labels: bug

#1357 feat: allow privacy zone updates for bcsc
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/bcsc-client.ts
Labels: enhancement

#1358 chore: disable bcsc
  app/jest/form.test.tsx
  app/schemas-ui/ui-gold.ts
  lambda/app/src/keycloak/integration.ts
Labels: enhancement

#1359 chore: release test
  app/components/Table.tsx
  app/jest/form.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/admin-dashboard.tsx
  app/pages/index.tsx
  app/schemas-ui/ui-gold.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/bcsc-client.ts
  lambda/shared/templates/sso-updates-mailing-list-message.html
  terraform/env-resources.tf_prod
Labels: release:minor

#1360 chore: release
  app/components/Table.tsx
  app/jest/form.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/page-partials/terms-conditions/Content.tsx
  app/pages/admin-dashboard.tsx
  app/pages/index.tsx
  app/schemas-ui/ui-gold.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/24.bcsc-api.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/keycloak/integration.ts
  lambda/app/src/queries/bcsc-client.ts
  lambda/shared/templates/sso-updates-mailing-list-message.html
  terraform/env-resources.tf_prod
Labels: release:minor

#1361 chore: permissions
  README.md
  terraform/provider.tf
  terraform/roles.tf
Labels: enhancement

#1362 fix: skip tls verification of certificate
  terraform/ecs.tf
Labels: bug
