Repository bcgov/sso-requests, pull requests merged in 2025-02, with the labels that each got.

#1375 feat: disable jwks_uri and update bcsc api conditionally
  lambda/__tests__/20.bcsc.test.ts
  lambda/app/src/bcsc/client.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/src/queries/request.ts
Labels: enhancement

#1376 feat: admin idir access
  app/jest/form.test.tsx
  app/schemas/providers-gold.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/app/src/controllers/requests.ts
Labels: enhancement

#1381 chore: npm audit
  app/next-env.d.ts
  app/package.json
  app/yarn.lock
Labels: enhancement

#1383 chore: version updates
  .github/workflows/deploy-gh-pages-maintenance.yml
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/k6-tests.yml
  .github/workflows/terraform.yml
  .github/workflows/test.yml
  .tool-versions
  app/next.config.js
  app/package.json
  docker-compose.yml
Labels: bug

#1384 chore: bump the reamining ubuntu 20
  .github/workflows/test.yml
Labels: dependencies

#1385 chore: idp selection
  app/form-components/FormTemplate.tsx
  app/form-components/widgets/TooltipIDPCheckboxesWidget.tsx
  app/next.config.js
  app/schemas-ui/ui-gold.ts
Labels: bug

#1386 chore: signing alg
  .github/workflows/terraform.yml
  lambda/app/src/bcsc/client.ts
  terraform/variables.tf
Labels: enhancement
