Repository bcgov/sso-requests, pull requests merged in 2025-01, with the labels that each got.

#1363 fix: client name updates at bcsc disabled
  lambda/app/src/controllers/requests.ts
Labels: bug

#1364 chore: release to test
  README.md
  lambda/app/src/controllers/requests.ts
  terraform/provider.tf
  terraform/roles.tf
Labels: ignore-for-release

#1365 chore: release
  README.md
  lambda/app/src/controllers/requests.ts
  terraform/provider.tf
  terraform/roles.tf
Labels: enhancement, release:patch

#1366 feat: disable idir for new integrations and grandfather existing ones
  app/jest/axe.test.tsx
  app/jest/filters.test.tsx
  app/jest/form.test.tsx
  app/jest/my-dashboard/my-projects/assignUsersToRoles.test.tsx
  app/jest/my-dashboard/my-projects/technicalDetails.test.tsx
  app/jest/ssoDashboard.test.tsx
  app/package.json
  app/schemas/providers-gold.ts
  app/tsconfig.json
  app/utils/helpers.tsx
  app/utils/status.ts
  app/yarn.lock
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/04.requests-by-teams.test.ts
  lambda/__tests__/20.bcsc.test.ts
  lambda/__tests__/21.requests-validations.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/__tests__/helpers/fixtures.ts
  lambda/__tests__/helpers/modules/common.ts
  lambda/app/src/controllers/requests.ts
  lambda/app/yarn.lock
  lambda/request-monitor/yarn.lock
  lambda/request-queue/yarn.lock
  lambda/siteminder-tests-scheduler/yarn.lock
  lambda/yarn.lock
  localserver/yarn.lock
Labels: enhancement

#1369 chore: remove IDIR e2e tests
  .github/workflows/e2e-keycloak.yaml
  app/cypress.config.ts
  app/cypress/appActions/Request.ts
  app/cypress/e2e/external/idpstopper-010-test7-8.cy.ts
  app/cypress/e2e/external/search-users.cy.ts
  app/cypress/fixtures/capitalization-fixtures.json
  app/cypress/fixtures/idim-search.json
  app/cypress/fixtures/idpstopper.json
  app/cypress/fixtures/requests-roles.json
  app/cypress/fixtures/requests.json
  app/cypress/fixtures/rolesusers.json
  app/cypress/fixtures/search-test-integration.json
  app/cypress/fixtures/sso-requests.json
  app/cypress/pageObjects/requestPage.ts
  app/cypress/support/commands.ts
  lambda/app/src/utils/constants.ts
  local/terraform/provider.tf
Labels: bug

#1370 chore: bump next
  app/package.json
  app/yarn.lock
Labels: enhancement

#1372 fix: full end-to-end tests
  .github/workflows/e2e-keycloak.yaml
  app/cypress/appActions/Request.ts
  app/cypress/appActions/Team.ts
  app/cypress/e2e/README.md
  app/cypress/e2e/external/idpstopper-010-test7-8.cy.ts
  app/cypress/e2e/external/idpstopper-020-test11.cy.ts
  app/cypress/e2e/external/idpstopper-040-ssosession.cy.ts
  app/cypress/e2e/external/idpstopper-050-login-page-name-capitalization.cy.ts
  app/cypress/e2e/external/search-users.cy.ts
  app/cypress/e2e/external/sso-020-sessions.cy.ts
  app/cypress/fixtures/idpstopper.json
  app/cypress/fixtures/idpstopper11.json
  app/cypress/fixtures/search-test-integration.json
  app/cypress/pageObjects/playgroundPage.ts
  app/cypress/pageObjects/requestPage.ts
  app/cypress/support/commands.ts
Labels: bug

#1373 feat: enable project name updates for saml clients
  app/schemas-ui/ui-gold.ts
  lambda/__tests__/03.requests-by-users.test.ts
  lambda/__tests__/04.requests-by-teams.test.ts
  lambda/app/src/utils/helpers.ts
Labels: enhancement

#1374 fix: selectors
  app/cypress/pageObjects/requestPage.ts
Labels: bug
