Repository bcgov/sso-requests, pull requests merged in 2025-06, with the labels that each got.

#1439 chore: update e2e tests
  .github/workflows/e2e-keycloak.yaml
  app/cypress.config.ts
  app/cypress/appActions/Navigation.ts
  app/cypress/e2e/external/idpstopper-010-test7-8.cy.ts
  app/cypress/e2e/external/idpstopper-020-test11.cy.ts
  app/cypress/e2e/external/idpstopper-050-login-page-name-capitalization.cy.ts
  app/cypress/e2e/external/search-users.cy.ts
  app/cypress/e2e/external/sso-020-sessions.cy.ts
  app/cypress/pageObjects/playgroundPage.ts
  app/cypress/support/commands.ts
  docker-compose.yml
  local/terraform/main.tf
Labels: enhancement

#1442 fix: email template
  app/shared/templates/remove-inactive-idir-user-from-team/index.ts
Labels: bug

#1443 chore: upgrade patroni image
  helm/values-b29129-dev.yaml
  helm/values-c6af30-dev.yaml
  helm/values.yaml
Labels: enhancement

#1444 fix: active integrations
  app/jest-api/18.request-monitor.test.ts
  app/queries/request.ts
Labels: bug

#1445 chore: backup container creation
  helm/backup-storage/Makefile
  helm/backup-storage/README.md
  helm/backup-storage/values-b29129-dev.yaml
  helm/backup-storage/values-b29129-prod.yaml
  helm/backup-storage/values.yaml
Labels: enhancement

#1448 chore: point local dev at correct terraform modules
  local/terraform/main.tf
Labels: dependencies

#1449 chore: add the backup container to helm chart
  .github/workflows/publish-image-api-nk.yaml
  .github/workflows/publish-image-cron-nk.yaml
  .github/workflows/publish-image-nk.yaml
  .github/workflows/publish-image.yaml
  docs/backup-restore-documentation.md
  helm/Chart.yaml
  helm/backup-storage/Makefile
  helm/backup-storage/values-b29129-dev.yaml
  helm/backup-storage/values-b29129-prod.yaml
  helm/backup-storage/values.yaml
  helm/values-b29129-dev.yaml
  helm/values.yaml
Labels: enhancement

#1450 chore: create service account script
  .github/workflows/publish-image.yaml
  service-account-generator/README.md
  service-account-generator/generate_sa.sh
  service-account-generator/templates/role-gold.yaml
Labels: enhancement

#1451 feat: create pz and ppid mappers for clients requesting otp integration
  app/keycloak/integration.ts
  app/keycloak/protocolMappers.ts
  helm/values-b29129-dev.yaml
  helm/values-c6af30-dev.yaml
Labels: enhancement

#1452 fix: updates to privacy zone and add client role mappers
  app/keycloak/integration.ts
  app/keycloak/protocolMappers.ts
Labels: enhancement
