Repository bcgov/sso-requests, pull requests merged in 2025-03, with the labels that each got.

#1387 chore: sig variable
  terraform/lambda-app.tf
  terraform/lambda-request-queue.tf
Labels: bug

#1389 chore: add the url decoding to the role names in the api
  lambda/__tests__/26.css-api-roles.test.ts
  lambda/css-api/src/routes.ts
  lambda/css-api/src/services/keycloak-service.ts
Labels: enhancement

#1390 chore: email diff
  lambda/__tests__/06.email-templates.test.ts
  lambda/__tests__/07.emails-for-user-requests.test.ts
  lambda/__tests__/08.emails-for-team-requests.test.ts
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/__tests__/helpers/common-mocks.js
  lambda/__tests__/helpers/fixtures.ts
  lambda/app/src/controllers/requests.ts
  lambda/package.json
  lambda/shared/templates/update-integration-applied/index.ts
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/index.ts
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
  lambda/shared/utils/ches.ts
  lambda/yarn.lock
Labels: enhancement

#1391 chore: email format
  lambda/__tests__/__snapshots__/06.email-templates.test.ts.snap
  lambda/shared/templates/update-integration-applied/update-integration-applied.html
  lambda/shared/templates/update-integration-submitted/update-integration-submitted.html
  lambda/shared/utils/ches.ts
Labels: enhancement

#1392 chore: logout
  app/pages/_app.tsx
  app/utils/openid.ts
  local/terraform/main.tf
Labels: bug

#1393 chore: email format
  lambda/shared/utils/ches.ts
Labels: enhancement

#1394 fix: bcsc attributes
  lambda/shared/utils/ches.ts
Labels: bug

#1395 chore: update the swagger docs
  lambda/css-api/src/routes.ts
Labels: documentation

#1397 chore: tf modules
  .github/workflows/e2e.yaml
  local/terraform/main.tf
Labels: bug

#1401 chore: admin filters
  app/interfaces/Request.ts
  app/jest/filters.test.tsx
  app/utils/helpers.tsx
Labels: enhancement

#1402 test: e2e social
  app/cypress/e2e/ci/integrations-crud.cy.ts
  app/cypress/fixtures/requests.json
  app/cypress/pageObjects/dashboardPage.ts
  app/cypress/pageObjects/requestPage.ts
  docker-compose.yml
Labels: enhancement

#1403 chore: add dc
  .github/workflows/deploy-gh-pages-maintenance.yml
Labels: bug
